# Generated by Django 4.0.4 on 2022-11-30 11:10

import accounts.utils.token_generator
import accounts.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'pending'), ('a', 'Accepted'), ('r', 'Rejected'), ('b', 'Blocked')], default='p', max_length=1)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='users/requests', validators=[accounts.utils.validators.validate_file_size])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('token', models.CharField(default=accounts.utils.token_generator.random_number, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
