# Generated by Django 4.0.4 on 2022-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_category_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
