# Generated by Django 4.0.4 on 2022-12-03 10:05

import accounts.utils.token_generator
import accounts.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0004_food_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('a', 'Accepted'), ('r', 'Rejected'), ('b', 'Blocked')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='token',
            field=models.CharField(default=accounts.utils.token_generator.random_number, max_length=15),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(upload_to='restaurant/profile', validators=[accounts.utils.validators.validate_file_size]),
        ),
    ]
