# Generated by Django 4.0.4 on 2022-12-06 10:33

import accounts.utils.token_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurant_slug_restaurant_date_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='food',
            name='slug',
        ),
        migrations.AddField(
            model_name='food',
            name='token',
            field=models.CharField(default=accounts.utils.token_generator.random_number, max_length=15),
        ),
    ]
