# Generated by Django 4.0.4 on 2022-07-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_food_inventory'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepared_items',
            field=models.ManyToManyField(blank=True, related_name='prepared_items', to='restaurant.food'),
        ),
    ]
