# Generated by Django 4.0.4 on 2022-12-10 09:55

import accounts.utils.token_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_prepared_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.CharField(default=accounts.utils.token_generator.random_number, max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Preparing', 'Preparing'), ('Sending', 'Sending'), ('Arrived', 'Arrived')], default='Ordered', max_length=10),
        ),
    ]
